### ISSUE TITLE
Create redirects for every page under `api-clients`

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#303]
For every rename we do in https://github.com/seamapi/docs/issues/304, we need to add a redirect to https://github.com/seamapi/docs/blob/beta/.gitbook.yaml

For example, if we do

```diff
- * [Access Control Systems](api-clients/access-control-systems/README.md)
+ * [Access Control Systems](api-clients/acs/README.md)
-  * [Systems](api-clients/access-control-systems/systems/README.md)
+  * [Systems](api-clients/acs/systems/README.md)
-    * [List Systems](api-clients/access-control-systems/systems/list-systems.md)
+    * [List Systems](api-clients/acs/systems/list.md)
```

Then we need to add

```yaml
redirects:
  api-clients/access-control-systems: api-clients/acs/README.md
  api-clients/access-control-systems/systems: api-clients/acs/systems/README.md
  api-clients/access-control-systems/systems/list-systems: api-clients/acs/systems/list.md
```

We can then find/replace all links in the docs to point to the new files.
